List<String> patologiasMaisVistas = [
  "Selecione",
  "Desidratação",
  "Insolação",
  "Exaustão por calor",
  "Hipoglicemia",
  "Desmaios",
  "Crises de ansiedade ou pânico",
  "Problemas respiratórios (asma, bronquite)",
  "Hipertensão arterial",
  "Distúrbios cardíacos (arritmia, infarto)",
  "Traumas devido a quedas ou empurrões",
  "Descompensação em diabéticos",
  "Síncope vasovagal (desmaio causado por estresse ou dor intensa)",
  "Alergias alimentares",
  "Alergias respiratórias (rinite, sinusite)",
  "Ferimentos leves (cortes, arranhões)",
  "Entorses e fraturas",
  "Infecções alimentares",
  "Problemas gastrointestinais (vômito, diarreia)",
  "Cãibras musculares",
  "Hipotermia (em eventos ao ar livre e em baixas temperaturas)",
  "Intoxicação alimentar",
  "Enxaqueca ou cefaleia (devido ao estresse, calor ou desidratação)",
  "Reações alérgicas a picadas de insetos",
  "Dores lombares (devido a longos períodos em pé)",
  "Abuso de álcool ou drogas",
  "Convulsões (em pessoas epilépticas ou com histórico de crises)",
  "Infecções urinárias (devido à falta de hidratação ou higiene)",
  "Picadas de insetos (em eventos ao ar livre)",
  "Acidentes vasculares cerebrais (AVC)",
  "Infecções de pele (contato com superfícies contaminadas)",
  "Problemas auditivos temporários (exposição a música alta)",
  "Lipotimia (desmaio por queda de pressão arterial)",
  "Crises alérgicas graves (anafilaxia)",
  "Ataques de pânico",
  "Queimaduras solares (exposição prolongada ao sol sem proteção)",
  "Lesões articulares (torções e luxações)",
  "Problemas oculares (irritação nos olhos devido à poeira ou poluição)",
  "Desidratação severa levando a choque hipovolêmico",
  "Problemas renais agudos (devido à desidratação prolongada)",
  "Desorientação e confusão mental (por desidratação ou insolação)",
  "Cortes ou lacerações graves (devido a acidentes ou multidões)",
  "Fraturas ósseas complexas",
  "Choque anafilático (em casos de alergias extremas)",
  "Hiperglicemia (especialmente em diabéticos mal controlados)",
  "Dores musculares severas (após esforço físico intenso)",
  "Outros"
];
