List<String> patologiasMaisVistas = [
  "Abuso de álcool ou drogas",
  "Acidentes vasculares cerebrais (AVC)",
  "Ataques de pânico",
  "Bolhas: Feridas nos pés",
  "Convulsões (em pessoas epilépticas ou com histórico de crises)",
  "Cortes ou lacerações graves (devido a acidentes ou multidões)",
  "Desidratação",
  "Desmaios: Perda de consciência",
  "Exaustão física",
  "Ferimentos leves (cortes, arranhões)",
  "Hipertensão (Pressão alta)",
  "Hipoglicemia (Queda de açúcar sem sangue)",
  "Hipotensão (Pressão baixa)",
  "Lesões por esforço repetitivo",
  "Problemas ortopédicos (Torções, fraturas ou dores musculares)",
  "Problemas respiratórios",
  "Reações alérgicas a picadas de insetos",
  "Traumas devido a quedas ou empurrões",
  "Outros"
];
