List<String> patologiasMaisVistas = [
  "Selecione",
  "Hipertensão (Pressão alta)",
  "Hipotensão (Pressão baixa)",
  "Desidratação",
  "Exaustão física",
  "Hipoglicemia (Queda de açúcar no sangue)",
  "Problemas ortopédicos (Torções, fraturas ou dores musculares)",
  "Desmaios: Perda de consciência",
  "Distúrbios cardíacos (arritmia, infarto)",
  "Traumas devido a quedas ou empurrões",
  "Bolhas: Feridas nos pés",
  "Lesões por esforço repetitivo",
  "Problemas respiratórios",
  "Ferimentos leves (cortes, arranhões)",
  "Reações alérgicas a picadas de insetos",
  "Abuso de álcool ou drogas",
  "Convulsões (em pessoas epilépticas ou com histórico de crises)",
  "Acidentes vasculares cerebrais (AVC)",
  "Ataques de pânico",
  "Cortes ou lacerações graves (devido a acidentes ou multidões)",
  "Outros"
];
